### ISSUE TITLE
build fails for newest version of IRIS

### ISSUE THREAD

**Issue by vicssun** [intersystems/Samples-FHIRStarter#17]
The namespace installer method has been changed in IRIS latest so now the build fails. It's a 1 line change to Installer.xml from the HS.HC.Util.Installer line, which needs to be replaced by:

`<Invoke Class="HS.Util.Installer.Foundation" Method = "Install" CheckStatus="true">`

**Comment by jmorg85-isc** [comment]
Thank you for the thorough reporting.  I have updated the class name to reflect the change in name.
