### ISSUE TITLE
Confusing Instructions, #4

### ISSUE THREAD

**Issue by nickmitchko** [intersystems/Samples-FHIRStarter#3]
The note about period confused multiple SEs as we wrongly assumed it was for step 4 and not step 3.

Can we change to this instead?

* Execute the Docker Run command by running the Docker Run command: 
```bash
docker run -d --hostname FHIRStarter -p 52773:52773 --init -v $PWD/ISC:/tmp/ISC --name FHIRStarter irishealth-fhirstarter-demo:1.0
```

Relevant section below...

## Installation instructions: 

1. Clone this repository: `git clone`.
2. Open the Terminal or command prompt window and change the directory to `FHIRStarterDemo`.
3. Execute the Docker Build command by running the Docker Build command: `docker build -t irishealth-fhirstarter-demo:1.0 .`
**Note:** the period at the end of the Docker Build command is **required**.
4. Execute the Docker Run command by running the Docker Run command: `docker run -d --hostname FHIRStarter -p 52773:52773 --init -v $PWD/ISC:/tmp/ISC --name FHIRStarter irishealth-fhirstarter-demo:1.0`.

**Comment by jmorg85-isc** [comment]
Retroactively closing issue.  The recommended clarification was incorporated in the readme.txt.

**Comment by jmorg85-isc** [comment]
Retroactively closing issue. The recommended clarification was incorporated in the readme.txt.
