### ISSUE TITLE
the url to access after `docker run`?

### ISSUE THREAD

**Issue by chihpoc** [intersystems/Samples-FHIRStarter#4]
After

4. Execute the Docker Run command by running the following:
   `docker run -d --hostname FHIRStarter -p 52773:52773 --init -v $PWD/ISC:/tmp/ISC --name FHIRStarter irishealth-fhirstarter-demo:1.0`

http://0.0.0.0:52773/ yields

`The requested URL / was not found on this server.`

What's the correct url after launching the docker container?

**Comment by jmorg85-isc** [comment]
Hello,

The InterSystems Management Portal is always hosted at /csp/sys/UtilHome.csp.  In your example, the full URL would be:

http://0.0.0.0:52773/csp/sys/UtilHome.csp.

Hope that helps clarify next steps.  For additional information on InterSystems technology, please take a look at [Using the Management Portal](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSA_using_portal) and [Running InterSystems Products in Containers](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/DocBook.UI.Page.cls?KEY=ADOCK).
