### ISSUE TITLE
Community License expired

### ISSUE THREAD

**Issue by toncatgm** [intersystems/Samples-FHIRStarter#6]
How do we get the following resolved:
 > [3/3] RUN iris start IRIS     && iris session IRIS -U %SYS "##class(%SYSTEM.OBJ).Load("/usr/irissys/mgr/Installer.xml","cdk")"     && iris session IRIS -U %SYS "##class(Demo.Installer).Install()"     && iris stop IRIS quietly:
#6 0.365 Using 'iris.cpf' configuration file
#6 0.506 
#6 0.888 This copy of InterSystems IRIS has been licensed for use exclusively by:
#6 0.888 Community License expired.
#6 0.888 Copyright (c) 1986-2021 by InterSystems Corporation
#6 0.888 Any other use is a violation of your license agreement
#6 3.277 
#6 3.277 Error: Invalid Community Edition license, may have exceeded core limit. - Shutting down the system : $zu(56,2)= 0Starting IRIS
#6 11.31 
#6 11.31 An error was detected during InterSystems IRIS startup.
#6 11.31 ** Startup aborted **
------

**Comment by nickmitchko** [comment]
Although buried, the [documentation here](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/DocBook.UI.Page.cls?KEY=ACLOUD#ACLOUD_image) describes this workaround.

**Comment by kandimallab** [comment]
I'm still getting the same error with the workaround. Any ideas on how to fix it?

![image](https://user-images.githubusercontent.com/32016424/169360519-d71618ae-672b-403f-bb58-9187254b6047.png)

**Comment by kandimallab** [comment]
> I'm still getting the same error with the workaround. Any ideas on how to fix it?
> 
> ![image](https://user-images.githubusercontent.com/32016424/169360519-d71618ae-672b-403f-bb58-9187254b6047.png)

I was able to fix this error by running building with limited cores (solution above) AND updating the Dockerfile with the latest irishealth-community version:

`FROM intersystems/irishealth-community:2021.2.0.651.0`

**Comment by jmorg85-isc** [comment]
Bhavya,

Thank you for your persistence on this issue and providing us with confirmation that you were able to solve the issue.

It is on my agenda to update and enhance this demonstration container this summer.  I will assure to 1) include these instructions in the readme and 2) confirm both sets of _docker build_ commands work with the soon to be released IRIS for Health 2022.1.

Regards,
Jeff Morgan
Sales Engineer
InterSystems
